---
- name: config
  hosts: ROUTERS
  gather_facts: false

  vars:
    cli:
      username: kbeyrouthy
      password: terminal@2016

  tasks:

    - name: Merge provided configuration with device configuration
  cisco.ios.ios_interfaces:
    config:
    - name: TenGigabitEthernet0/0/6
      description: Configured and Merged by Ansible Network
      enabled: true
    state: merged


